# Generated by Django 4.1.4 on 2023-01-13 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SPE_webapp', '0002_comments_customuser_post_alter_customuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SPE_webapp.comments'),
        ),
    ]
